<?php // -*-php-*-
  //
  // PlanetLab authentication and integration with Drupal
  //
  // Mark Huang <mlhuang@cs.princeton.edu>
  // Copyright (C) 2006 The Trustees of Princeton University
  //
  // $Id$
  //

require_once 'plc_config.php';
require_once 'plc_session.php';
require_once 'plc_functions.php';

function planetlab_help($section) {
  switch ($section) {
  case 'admin/modules#description':
    return t('Enables authenticated login via a PlanetLab API server.');
  }
}

function planetlab_info($field = 0) {
  $info['name'] = 'PlanetLab';

  if ($field) {
    return $info[$field];
  } else {
    return $info;
  }
}

function planetlab_menu($may_cache) {
  $items = array();

  if ($may_cache) {
    $items[] = array(
		     'path' => 'planetlab/logout',
		     'title' => t('Log out of %s', array('%s' => variable_get('site_name', 'local'))),
		     'callback' => 'planetlab_logout',
		     'access' => TRUE,
		     'type' => MENU_CALLBACK
		     );
    $items[] = array(
		     'path' => 'db',
		     'title' => variable_get('site_name', 'local'),
		     'callback' => 'planetlab_page',
		     'access' => TRUE,
		     'type' => MENU_CALLBACK
		     );
  }

  return $items;
}

// formatting helpers
function ul_start () { return '<ul class=menu>'; }
function ul_end () { return '</ul>'; }
function leaf($text) { return '<li class=leaf>' . $text . '</li>'; }
function expanded($text) { return '<li class=expanded>' . $text . '</li>'; }
function p($text) { return '<p>' . $text . '</p>'; }
// fake theme to look like menu
function menu_theme ($menu) {
  $result = '';
  $result .= ul_start();
  foreach ($menu as $item) $result .= $item;
  $result .= ul_end();
  return $result;
}

function planetlab_block($op = 'list', $delta = 0, $edit = array()) {
  global $user, $plc;

  if ($op == 'list') {
    $blocks[0]['info'] = t('PlanetLab login');

    return $blocks;

  } else if ($op == 'view') {
    $block = array();

    if (!$plc->person) {
      // Force login via HTTPS
      unset($_GET['time']);
      $form['#action'] = "https://" . $_SERVER['HTTP_HOST'] . url($_GET['q'], drupal_get_destination());
      $form['#id'] = 'planetlab-login-form';
      $form['name'] = array('#type' => 'textfield',
			    '#title' => t('E-mail'),
			    '#maxlength' => 60,
			    '#size' => 25,
			    '#required' => TRUE,
			    );
      $form['pass'] = array('#type' => 'password',
			    '#title' => t('Password'),
			    '#size' => 25,
			    '#required' => TRUE,
			    );
      $form['submit'] = array('#type' => 'submit',
			      '#value' => t('Log in'),
			      );

      $block['subject'] = t('%s login', array('%s' => variable_get('site_name', 'local')));
      $block['content'] = drupal_get_form('planetlab_login_block', $form, 'planetlab_login');
      $block['content'] .= p('');
      $block['content'] .= p( href (l_reset_password(),"Forgot your password?") );
      $block['content'] .= p( href(l_person_register(),"Create an account") );
      $block['content'] .= p( href(l_site_register(),"File a site registration") );
    } else {
      $block['subject'] = $plc->person['email'];
      $is_admin = in_array(10,$plc->person['role_ids']);
      $is_pi    = in_array(20,$plc->person['role_ids']);
      $is_user  = in_array(30,$plc->person['role_ids']);
      $is_tech  = in_array(40,$plc->person['role_ids']);

      $site_item = '';
      $site_item .= href(l_sites(),"Sites");
      $site_item .= ul_start();
      $site_item .= leaf( href(l_site(plc_my_site_id()),"My site"));
      if ( $is_admin ) 
	$site_item .= leaf( href(l_site_pending(),"Pending Requests"));
      if( $is_admin )
	$site_item .= leaf( href(l_site_status(),"Migration Status"));
      $site_item .= ul_end();
      $items[] = expanded($site_item);

      $user_item = '';
      $user_item .= href(l_persons(),'Users');
      $user_item .= ul_start();
      $user_item .= leaf( l_person_t(plc_my_person_id(),"My account"));
      if (is_pi) 
	$user_item .= leaf( href( l_persons_site(plc_my_site_id()), "My users"));
      if ( $plc->alt_person && $plc->alt_auth) {
	$email = $plc->person['email']; 
	$user_item .= leaf( href( l_sulogout(),"Log out of $email"));
      }	
      $user_item .= ul_end();
      $items [] = expanded($user_item);

      $node_item = '';
      $node_item .= href(l_nodes(),"Nodes");
      $node_item .= ul_start();
      $node_item .= leaf( href (l_nodes_site (plc_my_site_id()),"My Site Nodes"));
      $node_item .= leaf( href (l_node_add(),"Add Node"));
      if ( $is_admin) 
	$node_item .= leaf (href(l_peers(),'Peers'));
      $node_item .= ul_end();
      $items [] = expanded($node_item);

      $slice_item = '';
      //if( !( $is_tech && ! $is_user && ! $is_pi && ! $is_admin ) ) 
      $slice_item .= href(l_slices(),"Slices");
      $slice_item .= ul_start();
      if( $is_admin || $is_pi ) {
	$slice_item .= leaf(href(l_slice_add(),"Create Slice"));
      }
      if( !( $is_tech && ! $is_user && ! $is_pi && ! $is_admin ) ) 
	$slice_item .= leaf(href(l_sirius(),"Sirius"));
      $slice_item .= ul_end();
      $items [] = expanded($slice_item);

      if( $is_admin || $is_pi ) {
	$tag_item = '';
	$tag_item .= href(l_tags(),"All Tag Types");
	$tag_item .= ul_start();
	$tag_item .= leaf( href( l_tags_slice(),"Slice Tags"));
	$tag_item .= leaf( href( l_tags_interface(),"Interface Tags"));
	$tag_item .= leaf( href (l_tags_interface(),"Setting Types (dup xxx)"));
	$tag_item .= leaf( href( l_tags_node(),"Node Tags"));
	$tag_item .= leaf( href( l_nodegroups(),"Node groups (xxx)"));
	$tag_item .= ul_end();
	$items [] = expanded($tag_item);
      }

      $doc_item = '';
      $doc_item .= href(l_about(),'About MyPLC');
      $doc_item .= ul_start();
      $doc_item .= leaf ( href (l_doc_plcapi(),"PLCAPI doc"));
      $doc_item .= leaf ( href (l_doc_nmapi(),"NMAPI doc"));
      $doc_item .= ul_end();
      $items[] = expanded($doc_item);

      if ( $is_admin )
	$items[] = leaf (href(l_events(),'Events'));
      
      if ($user->uid) {
	// Drupal logout (destroys the session and cleans up $user)
	// Thierry unclear when this triggers, I suspect this is obsolete
	$items[] = leaf (l(t('Log out of %s', 
			     array('%s' => variable_get('site_name', 'local'))), 'logout'));
      } else {
	// PlanetLab logout (just destroy the session)
	$items[] = leaf ( href (l_logout(),'Log out'));
      }
      
      //$block['content'] = theme('list_item', $items);
      $block['content'] = menu_theme($items);
      //      plc_debug("content",$block['content']);
    }

    /*
     ob_start();
     print '<pre>';
     print_r($_SESSION);
     print '</pre>';
     $block['content'] .= ob_get_contents();
     ob_end_clean();
    */

    return $block;
  }
}

function planetlab_login_validate($form_id, $form_values) {
  global $user, $plc;

  if ($form_values['name'] && $form_values['pass']) {
    // Drupal login succeeded
    if (($user = user_authenticate($form_values['name'], trim($form_values['pass']))) &&
	$user->uid) {
      return;
    }

    $plc = new PLCSession($form_values['name'], $form_values['pass']);

    // PlanetLab login failed
    if (!$plc->person) {
      form_set_error('login', t('Sorry. Unrecognized username or password.'));
      watchdog('planetlab', t('Login attempt failed for %user.', array('%user' => theme('placeholder', $form_values['name']))));
    }

    // PlanetLab login succeeded
    else {
      // Login admins to Drupal as the superuser
      if (in_array('admin', $plc->person['roles'])) {
	$user = user_load(array('uid' => 1));
      }
    }
  }
}

function planetlab_login_submit($form_id, $form_values) {
  global $plc;

  // Our referring page is encased in a query string of the form
  // "destination=referrer".
  parse_str(drupal_get_destination()); // => $destination

  // The referrer itself is a URL path with the original query string,
  // e.g. "referer.php?query".
  extract(parse_url($destination)); // => $query

  // Which we then have to parse again as a query string.
  parse_str($query); // => $url

  if ($plc->person) {
    // To handle the edge case where this function is called during a
    // bootstrap, check for the existence of t().
    if (function_exists('t')) {
      $message = t('Session opened for %name.', array('%name' => theme('placeholder', $plc->person['email'])));
    }
    else {
      $message = "Session opened for ". check_plain($person['email']);
    }
    watchdog('planetlab', $message);

    if (empty($url)) {
      // Create a timestamped final URL so that browsers don't return the user to
      // a cached page (where it would appear as if they never logged in or out).
      return array('time='. time());
    } else {
      // Make sure that redirections are always local
      $url = urldecode($url);
      if ($url[0] != "/") {
	$url = "/$url";
      }
      Header("Location: $url");
      exit();
    }
  }
}

function planetlab_logout() {
  global $plc;

  if ($plc->person) {
    // Invalidate PlanetLab session
    $plc->logout();
    watchdog('planetlab', t('Session closed for %name.', array('%name' => theme('placeholder', $plc->person['email']))));
  }

  // Destroy the current session:
  session_destroy();

  // The time prevents caching.
  drupal_goto(NULL, 'time='. time());
}

function planetlab_user($type, &$edit, &$user, $category = NULL) {
  switch ($type) {
  case 'logout':
    if ($plc->person) {
      $plc->logout();
      watchdog('planetlab', t('Session closed for %name.', array('%name' => theme('placeholder', $plc->person['email']))));
    }
    break;
  }
}

function planetlab_page() {
  $path = $_SERVER['DOCUMENT_ROOT'] . preg_replace('/^db\//', '/planetlab/', $_GET['q']);

  // error_log("Requested " . $_GET['q'] . " -> $path");

  if (is_dir($path)) {
    foreach (array('index.php', 'index.html', 'index.htm') as $index) {
      if (is_file($path . "/$index")) {
	$path .= "/$index";
	break;
      }
    }
  }

  if (is_file($path)) {
    if (preg_match('/.php$/', $path)) {
      ob_start();
      include $path;
      $output = ob_get_contents();
      ob_end_clean();
    } else {
      $output = file_get_contents($path);
    }
    return $output;
  }
	    
  drupal_not_found();
}

function theme_planetlab($content) {
  return $content;
}

?>
